version: '3.1'

services:
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    command:
      - start-dev

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
